### ISSUE TITLE
Error compiling on iOS11.2

### ISSUE THREAD

**Issue by luco** [DylanVann/react-native-fast-image#112]
Anyone getting this on `react-native run`?

```
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImageView.h:22:12: note: previous definition is here
@interface FLAnimatedImageView : UIImageView
           ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:13:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.h:26:48: error: property has a previous declaration
@property (nonatomic, strong) FLAnimatedImage *animatedImage;
                                               ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImageView.h:26:48: note: property declared here
@property (nonatomic, strong) FLAnimatedImage *animatedImage;
                                               ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:13:
...node_modules/r
eact-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.h:27:35: error: property has a previous declaration
@property (nonatomic, copy) void(^loopCompletionBlock)(NSUInteger loopCountRemaining);
                                  ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImageView.h:27:35: note: property declared here
@property (nonatomic, copy) void(^loopCompletionBlock)(NSUInteger loopCountRemaining);
                                  ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:13:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.h:29:50: error: property has a previous declaration
@property (nonatomic, strong, readonly) UIImage *currentFrame;
                                                 ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImageView.h:29:50: note: property declared here
@property (nonatomic, strong, readonly) UIImage *currentFrame;
                                                 ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:13:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.h:30:52: error: property has a previous declaration
@property (nonatomic, assign, readonly) NSUInteger currentFrameIndex;
                                                   ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImageView.h:30:52: note: property declared here
@property (nonatomic, assign, readonly) NSUInteger currentFrameIndex;
                                                   ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:13:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.h:34:39: error: property has a previous declaration
@property (nonatomic, copy) NSString *runLoopMode;
                                      ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImageView.h:34:39: note: property declared here
@property (nonatomic, copy) NSString *runLoopMode;
                                      ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:32:1: error: duplicate interface definition for class 'FLAnimatedImage'
@interface FLAnimatedImage : NSObject
^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:32:12: note: previous definition is here
@interface FLAnimatedImage : NSObject
           ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:34:50: error: property has a previous declaration
@property (nonatomic, strong, readonly) UIImage *posterImage; // Guaranteed to be loaded; usually equivalent to `-imageLazilyCachedAtIndex:0`
                                                 ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:34:50: note: property declared here
@property (nonatomic, strong, readonly) UIImage *posterImage; // Guaranteed to be loaded; usually equivalent to `-imageLazilyCachedAtIndex:0`
                                                 ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:35:48: error: property has a previous declaration
@property (nonatomic, assign, readonly) CGSize size; // The `.posterImage`'s `.size`
                                               ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:35:48: note: property declared here
@property (nonatomic, assign, readonly) CGSize size; // The `.posterImage`'s `.size`
                                               ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:37:52: error: property has a previous declaration
@property (nonatomic, assign, readonly) NSUInteger loopCount; // 0 means repeating the animation i
ndefinitely
                                                   ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:37:52: note: property declared here
@property (nonatomic, assign, readonly) NSUInteger loopCount; // 0 means repeating the animation indefinitely
                                                   ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:38:55: error: property has a previous declaration
@property (nonatomic, strong, readonly) NSDictionary *delayTimesForIndexes; // Of type `NSTimeInterval` boxed in `NSNumber`s
                                                      ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:38:55: note: property declared here
@property (nonatomic, strong, readonly) NSDictionary *delayTimesForIndexes; // Of type `NSTimeInterval` boxed in `NSNumber`s
                                                      ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:39:52: error: property has a previous declaration
@property (nonatomic, assign, readonly) NSUInteger frameCount; // Number of valid frames; equal to `[.delayTimes count]`
                                                   ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:39:52: note: property declared here
@property (nonatomic, assign, readonly) NSUInteger frameCount; // Number of valid frames; equal to `[.delayTimes count]`
                                                   ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:41:52: error: property has a previous declaration
@property (nonatomic, assign, readonly) NSUInteger frameCacheSizeCurrent; // Current size of intelligently chosen buffer window; can range in the interval [1..frameCount]
                                                   ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:41:52: note: property declared here
@property (nonatomic, assign, readonly) NSUInteger frameCacheSizeCurrent; // Current size of intelligently chosen buffer window; can range in the interval [1..frameCount]
                                                   ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:42:42: error: property has a previous declaration
@property (nonatomic, assign) NSUInteger frameCacheSizeMax; // Allow to cap the cache size; 0 means no specific limit (default)
                                         ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:42:42: note: property declared here
@property (nonatomic, assign) NSUInteger frameCacheSizeMax; // Allow to cap the cache size; 0 means no specific limit (default)
                                         ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:58:49: error: property has a previous declaration
@property (nonatomic, strong, readonly) NSData *data; // The data the receiver was initialized with; read-only
                                                ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:58:49: note: property declared here
@property (nonatomic, strong, readonly) NSData *data; // The data the receiver was initialized with; read-only
                                                ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:62:29: error: redefinition of 'FLLogLevel'
typedef NS_ENUM(NSUInteger, FLLogLevel) {
                            ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:62:29: note: previous definition is here
typedef NS_ENUM(NSUInteger, FLLogLevel) {
                            ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:63:5: error: redefinition of enumerator 'FLLogLevelNone'
    FLLogLevelNone = 0,
    ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulat
or/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:63:5: note: previous definition is here
    FLLogLevelNone = 0,
    ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:64:5: error: redefinition of enumerator 'FLLogLevelError'
    FLLogLevelError,
    ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:64:5: note: previous definition is here
    FLLogLevelError,
    ^
In file included from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m:16:
...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.h:65:5: error: redefinition of enumerator 'FLLogLevelWarn'
    FLLogLevelWarn,
    ^
In module 'FLAnimatedImage' imported from ...node_modules/react-native-fast-image/ios/Vendor/SDWebImage/SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.h:14:
...ios/build/Build/Products/Debug-iphonesimulator/FLAnimatedImage.framework/Headers/FLAnimatedImage.h:65:5: note: previous definition is here
    FLLogLevelWarn,
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

It just started this after updating Xcode to iOS 11.2.

**Comment by gianpaj** [comment]
check #46 

I fixed it by opening Xcode and clicking 'Project' -> 'Clean' from the top menu.

**Comment by tonygentilcore** [comment]
This is a dupe of #46. It's an annoying issue that keeps happening to me and the solution is always some amount of cleaning, removing, reinstalling, etc. but it always takes me a few tries to get things straightened out. Really wish there were a real fix :-(

**Comment by luco** [comment]
I agree with @tonygentilcore. Cleaning doesn't solve the problem. It keeps coming back.

**Comment by tomauty** [comment]
Try Shift+<, Build phase, uncheck `Parallelize Build`

**Comment by eballeste** [comment]
this started to happen to me once i upgraded my os to sierra and xcode from 8.3 to 9.2.

no amount of cleaning, rebuilding, deleting the derived data folders, unlinking / linking, upgrading rn-fast-image from 1.0.0 to 2.0.1, etc etc. will get my build to run completely with `react-native run-ios`, always fails, works when built from xcode...

**Comment by DylanVann** [comment]
It's unfortunate that there are so many sources of this sort of issue. I commented on it in the duplicate issue: https://github.com/DylanVann/react-native-fast-image/issues/46#issuecomment-373993701
