### ISSUE TITLE
Issue with react-native-image-progress

### ISSUE THREAD

**Issue by Amurmurmur** [DylanVann/react-native-fast-image#148]
When using FastImage with react-native-image-progress as suggested in this post:
https://github.com/DylanVann/react-native-fast-image/issues/9#issuecomment-320849198

The loading indicator keeps spinning forever if the image is already in cache.
Both iOS and Android.

However if react-native-image-progress is used with the standard Image component that comes with the React-Native library, everything is fine.

Hopefully @DylanVann will be able to have a look as soon as he finds some time.

**Comment by cyclops24** [comment]
@Amurmurmur , @DylanVann I confirm this issue.
Anyone have any suggestion?

**Comment by DanielBoening** [comment]
same here.

**Comment by DylanVann** [comment]
This should be resolved now. See: https://github.com/DylanVann/react-native-fast-image/pull/74

**Comment by mnlbox** [comment]
It's still not working on Android :disappointed: 
Please reopen issue until complete fix.

**Comment by Amurmurmur** [comment]
@mnlbox Latest react-native-fast-image fixes the issue I've mentioned.
Try to upgrade `react-native-fast-image` and `react-native-image-progress` to the latest versions, clear all caches and rebuild the app.
