### ISSUE TITLE
Error:Tried to register two views with the same name FastImageView

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [DylanVann/react-native-fast-image#202]

**Comment by NrqhEIcsRi004** [comment]
The problem has been solved and it seems that the version number is different.

**Comment by drewandre** [comment]
I'm still seeing this in v7.0.2 when I have the same version of fastlane imported from a shared folder in a mono repo environment. Running `npm dedupe` is a temporary fix.

**Comment by RajeshRRathod** [comment]
i face same error like Tried to register two views with the same name FastImageView in my working project

**Comment by dbotman** [comment]
I get the same error:

ERROR Invariant Violation: Tried to register two views with the same name FastImageView

Does anyone have a solution yet?

react-native-image-modal@2.0.3
react-native-fast-image@8.3.7
expo@40.0.1
react-native@0.63.4
react@16.13.1

**Comment by kabeza** [comment]
Same error using FastImage inside a custom component assigned to a FlatList's renderItem

**Comment by chubo274** [comment]
i got the same issue.

on     "react-native-fast-image": "^8.6.3",
    "react-native": "0.70.5",
    
i had tried `npm dedupe` but still same error

**Comment by Danushka96** [comment]
@drewandre Hi, Did you able to resolve this issue in a mono repo environment?
