### ISSUE TITLE
Memory leak: App crashes when it load more than 300 WebP images

### ISSUE THREAD

**Issue by aibrahim3546** [DylanVann/react-native-fast-image#622]
**Describe the bug**
I am using a WebP image. the memory get so hight up to 1gb when i try to load more that 300 image. And end up crashing the app because of out of memory.

**To Reproduce**
Try to load more than 300 WebP images.

**Expected behavior**
Memory doesn't leak and wont crash the app. Are there anyway that i can clear the memory?

**Dependency versions**

- React Native version: 0.61.4
- React version: 16.9.0
- React Native Fast Image version: 7.0.2

**Comment by dreampiggy** [comment]
Upgrade the SDWebImageWebPCoder to  v 0.5.0 should fix this issue. See 

This is not a memory leak, but just the memory usage is high.

**Comment by klaaz0r** [comment]
@dreampiggy is this fixes in the latest version of NPM? I still get huge spikes in memory usages

**Comment by dreampiggy** [comment]
@klaaz0r  Doesn't this issue been fixed ?

In the 0.5.0 we optimize the Static WebP images, which does not cause double RAM usage. (previouslly it allocate the same size `CGContext` as pixel size, means 2x RAM usage. But CGContext is useless for Static WebP.

**Comment by dreampiggy** [comment]
If you already use tons of WebP images and Animated Webp, maybe this 0.5.0 upgrade does not fix the issue from stratch. Because bitmap image always need RAM to allocate.

You can try to limit your image size, by changing the original image (let your image server provide to provide a smaller size). Or you can use the thumbnail decoding feature. See: [Thumbnail Decoding](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#thumbnail-decoding-550).

But those feature only available in iOS native code, there are no React JavcScript bridge currently...

**Comment by klaaz0r** [comment]
@dreampiggy I think the problem I am having is caused by something else, I did some comparison and loading in a few hundred images inside a flatlist didn't result in any problems. Memory spikes occurred when image urls got a 404 (or any other non-200). 
I made an issue here: 
https://github.com/DylanVann/react-native-fast-image/issues/635

**Comment by dreampiggy** [comment]
@klaaz0r Can you provide a demo to show the 404 case that cause OOM ?

For iOS part of reat-native-fast-image (using SDWebImage), once a image url was returned 404, it will be blacked list (until you disbale this feature). Even you disable black list, this does not cause Bitmap allocation which result so huge RAM usage.

I guess there are some leak in here.

**Comment by klaaz0r** [comment]
@dreampiggy I will create a repo with some examples showing what happens!  If you want to quickly test it yourself you can try to add some dead links/link responding with text inside the examples

**Comment by dreampiggy** [comment]
Have a try with SDWebImage 5.7.2 + and SDWebImageWebPCoder 0.5+.

See changelog:

SDWebImage [5.7.2](https://github.com/SDWebImage/SDWebImage/releases/tag/5.7.2) version released. I think this solve some OOM issue for large number of images using in `SDAnimatedImageView`.

**Comment by DylanVann** [comment]
Might be fixed by latest updates to SDWebImage (thanks @dreampiggy). Give it a shot. If not open a new issue. Thank you!

**Comment by Stafox** [comment]
Looks like the issue still exists. Created the new issue #738
