### ISSUE TITLE
crash on launch after FastImage.preload()

### ISSUE THREAD

**Issue by busterbogheart** [DylanVann/react-native-fast-image#809]
After adding the latest react-native-fast-image, I've attempted a preload() and instead received:

```
08-09 21:57:20.062 28825 29127 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.dylanvann.fastimage.FastImageViewManager
08-09 21:57:21.323 28825 28825 E AndroidRuntime: at com.dylanvann.fastimage.FastImageViewModule$1.run(FastImageViewModule.java:34)
```

I've run react-native-clean-project and reset metro cache, etc, but no change.

**Expected behavior**
Not crash on launch

**Dependency versions**
- React Native version:  62.2
- React version:
- React Native Fast Image version: latest

**Comment by ReemaVinodGangdev** [comment]
Same Issue. Did anyone find solution?

**Comment by haibert** [comment]
it crashes even inside a try catch block, its a native error I guess ? :/ really wish this was fixed..

**Comment by timothyerwin** [comment]
Yeah, I'm getting the same. In a try/catch it's still crashing the whole app

**Comment by ashkanahrabi** [comment]
I have the same issue. Any updates on this?

**Comment by DylanVann** [comment]
Fixed in 8.6.15 (#1099): `FastImage.preload()` on Android now skips a `uri` that can't be resolved instead of crashing. Please open a new issue if you still see this on the latest version.
